/*
 * This source file was generated by the Gradle 'init' task
 */
package fun.lupus

import spock.lang.Specification

class AppTest extends Specification {
    def "BotConfig loads command prefix"() {
        setup:
        System.setProperty('COMMAND_PREFIX', '!')

        when:
        def prefix = BotConfig.commandPrefix

        then:
        prefix == '!' || prefix == null  // Either set or uses default
    }

    def "GoogleSheetsService class exists"() {
        expect:
        GoogleSheetsService.class != null
    }

    def "DiscordBot class exists"() {
        expect:
        DiscordBot.class != null
    }
}

